[package]
name = "adams_leaf"
version = "0.1.0"
authors = ["DavidYo <lturtsamuel@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5.5"

[lib]
name = "adams_lib"
path = "src/lib.rs"

[[bin]]
name = "adams_bin"
path = "src/bin.rs"
